name: android

# build on c/cpp changes or workflow changes
on:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'Android/**'
      - '.github/workflows/android.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'Android/**'
      - '.github/workflows/android.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: gradle
    - name: Install GNU gettext
      run: sudo apt install -y gettext
    - name: Build with Gradle
      run: cd Android && sudo ./gradlew assembleDebug
    - name: Save armeabi artifact
      uses: actions/upload-artifact@v4
      with:
        name: armeabi-v7a.apk
        path: Android/app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
    - name: Save arm64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: arm64-v8a.apk
        path: Android/app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
    - name: Save x86_64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: x86_64.apk
        path: Android/app/build/outputs/apk/debug/app-x86_64-debug.apk
